---
- hosts: WebServer
  tasks:
    - name: "Uninstall NginX"
      apt:
        name: nginx
        state: absent

    - name: "Stop Nginx Services"
      service:
        name: nginx
        state: stopped
